#-------------------------------
# General Site Settings

title: Hi, I'm Anusha
description: Back-end Developer // Database Designer // Avid Reader 
email: anusha.ksr18@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: References, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+/'
  rel-publisher: 'https://plus.google.com/u/0/+/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Anusha specializes in making things** for organizations.
  She has the expertise in [Back-end Web Development](#){:target="_blank"},
  but also puts effort into [Data Analysis](#){:target="_blank"}
  and [Database Architecture](#){:target="_blank"}.


skills:
- {name: Python, value: '9'}
- {name: R, value: '7'}
- {name: ASP.NET, value: '10'}
- {name: Database Design, value: '6'}
- {name: C, value: '7'}
- {name: C++, value: '5'}
- {name: Java, value: '8'}
- {name: SAS, value: '6'}

#-------------------------------
# Work Section

projects:
- {name: TYPO International Design Talks, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: City-IN website concept, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Crispy Icons, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Fresh It Up, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'face-aaroni.jpg',
  name: 'Ajay',
  title: 'Senior Project Manager, Infosys',
  quote: '<p><strong>While we all felt that Anusha was a great</strong> asset to our team — and really worked hard to understand our products from the point of view of the customer — we also all agree she should shower more often.</p>',
  logo: 'infosys.png'}
- {avatar: 'face-atariboy.jpg',
  name: 'Hank McCoy',
  title: 'Eater of Salad, Antartica Int.',
  quote: '<p><strong>Working with Anusha was the highlight of my career.</strong> </p>',
  logo: 'logo2.png'}



#-------------------------------
# Contact Section

social:
- {icon: 'github', link: 'http://github.com/#'}
- {icon: 'facebook', link: 'https://www.facebook.com/anusha.emmekar.5/'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/anuem/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
